# Input with workflow

name: Terraform CI

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Plan/apply/destroy'
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
      environment:
        description: 'Environment to deploy (dev/prod)'
        required: true
        type: choice
        options:
          - dev
          - prod

env:
  terraform_version: 1.13.3
  working_directory: ./infra
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: 'Terraform ${{ github.event.inputs.terraform_action }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Terraform Init
        working-directory: ${{ env.working_directory }}
        run: |
          terraform init \
            -backend-config=vars/${{ github.event.inputs.environment }}.tfbackend

      - name: Terraform Plan
        if: github.event.inputs.terraform_action == 'plan'
        working-directory: ${{ env.working_directory }}
        run: |
          terraform plan \
            -var-file=vars/${{ github.event.inputs.environment }}.tfvars

      - name: Terraform Apply
        if: github.event.inputs.terraform_action == 'apply'
        working-directory: ${{ env.working_directory }}
        run: |
          terraform apply \
            -var-file=vars/${{ github.event.inputs.environment }}.tfvars \
            -auto-approve

      - name: Terraform Destroy
        if: github.event.inputs.terraform_action == 'destroy'
        working-directory: ${{ env.working_directory }}
        run: |
          terraform destroy \
            -var-file=vars/${{ github.event.inputs.environment }}.tfvars \
            -auto-approve